services:
  db:
    image: mysql
    container_name: my_database
    environment:
      MYSQL_DATABASE: dalei
      MYSQL_ROOT_PASSWORD: Fnst*1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the initialization script

volumes:
  db_data: